.github/workflows/nightly.yml, .github/workflows/presubmit.yml, libshpool/src/attach.rs, libshpool/src/common.rs, libshpool/src/daemon/etc_environment.rs, libshpool/src/daemon/keybindings.rs, libshpool/src/daemon/server.rs, libshpool/src/daemon/shell.rs, libshpool/src/daemon/signals.rs, libshpool/src/daemon/ttl_reaper.rs, libshpool/src/detach.rs, libshpool/src/duration.rs, libshpool/src/kill.rs, libshpool/src/lib.rs, libshpool/src/protocol.rs, libshpool/src/test_hooks.rs, shpool/src/main.rs, shpool/tests/attach.rs, shpool/tests/daemon.rs, shpool/tests/support/daemon.rs, shpool/tests/support/events.rs, shpool/tests/support/mod.rs
This patch configures shpool to start using github actions for CI. It is cribbed from
[wprs](https://github.com/wayland-transpositor/wprs/tree/master/.github/workflows).
=> add github ci config

Cargo.lock, debian/changelog, libshpool/Cargo.toml, shpool/Cargo.toml
=> cut v0.6.0

libshpool/src/daemon/shell.rs, shpool/tests/attach.rs
This patch contains some attempted fixes for nightly CI failures. https://github.com/shell-pool/shpool/actions/runs/8641794383 contains the problems this is attempting to fix.
=> fix ci failures

libshpool/src/daemon/control_codes.rs, libshpool/src/daemon/server.rs, libshpool/src/daemon/shell.rs, shpool/tests/attach.rs
The current `motd = "dump"` mode will mangle the
first shell prompt that gets printed. There were
two problems, both of which are fixed in this
patch.
The first problem, was that we were only matching
on the first control code that `clear` emits. To
fix this this patch starts resolving the clear control codes emperically rather than through terminfo queries.
The second problem was that our motd splicing logic was buggy and would cause the next chunk after
the motd chunk to include a bunch of trailing zeros.
=> fix motd = "dump" mode

Cargo.lock, debian/changelog, libshpool/Cargo.toml, shpool/Cargo.toml
=> cut v0.6.1

Cargo.lock, debian/changelog, libshpool/Cargo.toml, shpool/Cargo.toml, shpool/tests/attach.rs
=> cut v0.6.2

README.md
This patch adds a section comparing shpool to
simillar tools to the README. It is good to
show that we are aware of simillar tools
and provide a writeup of the different options
so people can choose the right one for them
if shpool is not the best fit for them.
=> add comparison section to readme

CONFIG.md, README.md, libshpool/src/config.rs
This patch expands the documentation of configuration options, creating a dedicated file for it.
=> expand config documentation

libshpool/src/attach.rs, shpool/tests/attach.rs
These will just cause confusion in list output
and are likely not a good idea.
Fixes #51
=> disallow blank sessions

README.md
This patch links to the troubleshooting wiki page from the README. It to help address #64.
=> link to the troubleshoting guide from the README

libshpool/src/daemon/server.rs
This patch will hopefully address #59. Unfortunately, I wasn't able to write a test to reproduce the issue, so it is just a blind fix.
=> avoid err if we can't resolve terminfo for TERM

libshpool/src/config.rs, libshpool/src/daemon/server.rs, libshpool/src/daemon/show_motd.rs, shpool/tests/attach.rs, shpool/tests/data/motd_pager_1d_debounce.toml.tmpl, shpool/tests/data/motd_pager_1s_debounce.toml.tmpl
This should make the motd pager mode much less annoying by allowing people to set up their shpool to only show the motd every day or every few days.
Closes #31
=> teach motd.pager to allow debouncing

Cargo.lock, debian/changelog, libshpool/Cargo.toml, shpool/Cargo.toml
=> cut v0.6.3

Cargo.lock, libshpool/Cargo.toml, libshpool/src/config.rs, libshpool/src/hooks.rs, shpool-protocol/src/lib.rs
We hardly use this and the author has decided
to begin poisoning their dep tree with copyleft
adjacent licences. Let's cut and run while it
is still easy.
Closes #133
=> rip out directories dep

libshpool/src/daemon/server.rs, libshpool/src/daemon/shell.rs
This patch renames the "reader" thread to
be called "shell_to_client" or "shell->client"
instead. "Reader" is confusing because both of
the IO threads read data. This has been annoying
me for a little while, and I decided to rip
the bandaid off here.
=> reader thread -> shell_to_client thread

README.md
Show an example of defining multiple named sessions in a single ssh config block.
=> README: Better ssh config example

libshpool/src/daemon/exit_notify.rs, libshpool/src/daemon/trie.rs, rustfmt.toml, shpool/tests/support/daemon.rs
The fmt check has been failing in CI. This
patch fixes it.
=> fix: style

libshpool/src/daemon/server.rs, libshpool/src/daemon/shell.rs
This patch fixes an issue where we would lock up the whole daemon if the shell->client thread stopped
answering. Eventually we would try to talk to
the stuck thread with the global shells lock,
which pretty much makes all endpoints hang.
Adding timeouts to all our RPCs to the thread
should at least prevent the daemon from completely locking up, but the issue causing this to happen
in the first place is still there. We might just
need to clean up the session in question, but it
could also be some other timing issue.
=> fix: deadlock when shell->client thread stops

README.md
=> docs: link to release notes from README

libshpool/src/daemon/shell.rs
This patch fixes an issue where `shpool attach` would immediately
hang up while trying to reconnect to a session containing a large
restore buffer. The problem was that the heartbeat thread would
time out requesting a heartbeat from the shell->client thread
because it was busy cooking up the giant restore buffer. This
would lead all the other client threads to exit because they
think the socket connection is unhealthy despite it being
completely fine. The fix is simply to `continue` in the face
of a send timeout in the heartbeat thread rather than tearing
everything down.
=> fix: reconnect hangup due to long session restore
