shell-pool/shpool

- libshpool/src/user.rs
I've always been uncomfortable with the use of getpwuid and errno. It feels gross to directly mutate a global variable even though that is what the man page for getpwuid says you are supposed to do. I think the old code was ok in terms of errno (though I was forgetting to check for NULL return values) because errno is thread-local, but I still don't like it. More worrying is that the man page says "The return value may point to a static area, and may be overwritten by subsequent calls to getpwent(3), getpwnam(), or getpwuid()." This could be an issue because user::info() is called within spawn_subshell, which itself is called right at the start of a new connection. Each connection gets its own dedicated thread, so there could potentialy be a race between two calls to user::info(). In most …
> switch getpwuid -> getpwuid_r

- .github/workflows/nightly.yml
- .github/workflows/presubmit.yml
- Cargo.lock
- libshpool/Cargo.toml
- rust-toolchain.toml
- shpool/Cargo.toml
- shpool/tests/support/daemon.rs
This patch updates deps in a semver-compatible way in order to fix
https://github.com/shell-pool/shpool/security/dependabot/1.
> upgrade deps to fix security alert

- libshpool/src/daemon/server.rs
- shpool/tests/data/custom_detach_keybinding.toml
- shpool/tests/data/disable_symlink_ssh_auth_sock.toml
- shpool/tests/data/forward_env.toml
- shpool/tests/data/long_noop_keybinding.toml
- shpool/tests/data/no_etc_environment.toml
- shpool/tests/data/norc.toml
- shpool/tests/data/restore_lines.toml
- shpool/tests/data/restore_many_lines.toml
- shpool/tests/data/restore_screen.toml
- shpool/tests/data/user_env.toml
The 'prompt_prefix' option has had a while to bake and I have not gotten any bikeshedding suggestions beyond the one I've been using, so this patch
sets a new default prompt prefix. Users should no
longer need to worry about adding shell config to
make their prompt indicate they are in a shpool
session, they should get it for free from now on.
This change can be disabled by setting prompt_prefix="" in the config file.
> set a default prompt prefix

- Cargo.lock
- libshpool/Cargo.toml
- libshpool/src/config.rs
- libshpool/src/consts.rs
- libshpool/src/daemon/mod.rs
- libshpool/src/daemon/pager.rs
- libshpool/src/daemon/server.rs
- libshpool/src/daemon/shell.rs
- libshpool/src/daemon/show_motd.rs
- libshpool/src/tty.rs
- shpool/tests/attach.rs
- shpool/tests/daemon.rs
- shpool/tests/data/motd_pager.toml.tmpl
- shpool/tests/detach.rs
- shpool/tests/kill.rs
- shpool/tests/list.rs
- shpool/tests/support/daemon.rs
This is chained on https://github.com/shell-pool/shpool/pull/6, I'll rebase before merging
This patch adds a new pager mode for displaying the
motd. The difference between the normal dump mode
and the pager mode is that the pager will always
display the motd, regardless of if a user is making
a new session or reattaching to an old session.
Rather than using Pager(String) for the enum variant
I decided to go with a slightly more verbose struct
enum variant so that there is room to add more options
to this mode. I'm anticipating that users may want
something like the ability to set a cooldown time
so that this does not trigger on every reattach, but
does trigger on the first reattach done in a day.
For now, I'm not including any such options, but I
want to be able to add them in a backwards …
> add motd pager mode

- Cargo.lock
- libshpool/Cargo.toml
- libshpool/src/attach.rs
- libshpool/src/daemon/mod.rs
- libshpool/src/daemon/shell.rs
- libshpool/src/daemon/show_motd.rs
- libshpool/src/tty.rs
- shpool/Cargo.toml
- shpool/src/main.rs
This patch fixes an issue where shpool would not forward the x and y pixel values from the term size struct. These fields are not consistently set by terminal emulators, but some of them do set them correctly and some client programs rely on them. We should do our part by shuttling them along.
I switched to using the pure-rust version of motd to avoid an issue with slow startup times that was causing test timing issues. This also makes the open source shpool work the same way as our google internal version and means that we have a smaller unsafe footprint, which is probably good.
I spent some effort trying to write a test for this, but could not get wrapping the `shpool attach` subprocess in a pty to work for whatever reason. I don't think it is worth the effort.
Fixes #13
> forward {x,y}pixel in term size

- libshpool/src/daemon/pager.rs
- libshpool/src/daemon/server.rs
- shpool/tests/kill.rs
Issue #17 describes a problem where we seem to
occasionally deadlock when the session message
handler holds the session message lock open for
a while. This patch adds some additional logging
and also adds some timeouts to the sends. The logging should help get to the root cause if it comes up
again and the timeouts on the sends should make
it so the daemon does not get completely wedged
when this happens.
> add timeouts to session_message sends

- Cargo.lock
- deny.toml
- libshpool/Cargo.toml
- libshpool/src/attach.rs
- libshpool/src/config.rs
- libshpool/src/daemon/mod.rs
- libshpool/src/daemon/server.rs
- libshpool/src/daemon/shell.rs
- shpool/tests/attach.rs
- shpool/tests/data/dynamic_config.toml.tmpl
This patch teaches the shpool daemon to automatically pick up changes to the config when a user writes a new value. Right now, people need to restart the daemon every time they make a config change, which is pretty disruptive because it means losing sessions. Now
people can tweak config without losing sessions.
Fixes #20
> automatically reload config on changes

- libshpool/src/daemon/prompt.rs
This patch fixes an issue with the bash prompt prefix injection script. It turns out PROMPT_COMMAND is actually a list of functions to invoke rather than a single function. This brings the bash implementation more in line with the zsh and fish implementations and makes it work correctly with multi-function prompt hooks.
> fix bash prompt prefix injection script

- Cargo.lock
- deny.toml
- libshpool/Cargo.toml
- libshpool/src/consts.rs
- libshpool/src/daemon/prompt.rs
- libshpool/src/daemon/server.rs
- libshpool/src/daemon/shell.rs
- libshpool/src/lib.rs
- shpool/tests/attach.rs
- shpool/tests/daemon.rs
This patch teaches shpool to discern the shell it is launching
more accurately than we were doing in the past. Previously
we would just look at the name of the shell binary, but it
turns out this does not work well when people put `exec fish`
in their .bashrc or something similar. There are actually
some good reasons for people to do this rather than use chsh
or equivalent, so we should handle this usecase.
I tried a few different approaches to this before settling
on injecting a startup sentinal to the real shell, then
scanning for it and sniffing based off the pid once the
shell is fully started up. This ought to give the rc
files enough time to get processed, and it allows
us to avoid depending on an external binary like `ps`.
One drawback is that this won't work on non-linux,
so we …
> sniff shells for prompt injection

- Cargo.lock
- libshpool/Cargo.toml
This will make it so we no longer require libpam
to build.
Fixes #42
> bump motd to 0.2.2

- README.md
This patch adds a link to the wiki from the README so that people will be able to find it. Shpool is (hopefully) a tool that will be able to fit into different people's workflows in lots of different ways, and the wiki will be a good place for folks to share their tricks. We already have one such tip in there.
Closes #49
> link to wiki from README

- Cargo.lock
- libshpool/Cargo.toml
- libshpool/src/config.rs
- libshpool/src/config_watcher.rs
- libshpool/src/lib.rs
- shpool/tests/attach.rs
- shpool/tests/support/daemon.rs
- Fix a small issue in test about XDG_RUNTIME_DIR handling
- Simple merging logic for `Config`
- Load config from system-wide locations (fixes #30)
- Dynamically pick up changes from newly created config files (fixes #29)
- Use `directories-rs` to find the user-level config directory path (We should also consider using it for `XDG_RUNTIME_DIR` later)
Please see the commit message for a more detailed description of the change.
@ethanpailes currently, the config merging rule is very simple: higher-priority top-level keys always fully overwrite lower-priority ones. However we should probably handle arrays and maps differently. Let me know what you think is the best strategy.
Also the PR is fairly large, let me know how I can make it easier to review.
> Configuration loading overhaul

- libshpool/src/daemon/prompt.rs
- libshpool/src/daemon/server.rs
- libshpool/src/daemon/shell.rs
This patch makes shpool truely do nothing when the user has blanked out their prompt prefix. Previously, we were just not running any shell setup code, but we were still emitting sentinals. This is bad because it means
that users who have written interactive code in their startup files cannot use shpool at all.
Fixes #64
> avoid prompt setup code when prompt_prefix = ""

- libshpool/src/attach.rs
- shpool/tests/attach.rs
Whitespace in session names mangles list output
and is just generally confusing. I don't see a reason for it (though if someone has a usecase, this decision can be rolled back, we can solve the list issue with quoting or a json format or something).
Fixes #60
> ban whitespace in session names

- .github/dependabot.yml
- .github/workflows/build_binaries.yml
- .github/workflows/nightly.yml
- .github/workflows/presubmit.yml
- .github/workflows/publish.yml
- HACKING.md
- release-plz.toml
* Enable release-plz to create release PRs automatically
* Enable automatic binary builds on Linux
* Enable version updates for rust and github actions using dependabot
Required repo secrets are
* `RELEASE_PLZ_APP_ID` and `RELEASE_PLZ_APP_PRIVATE_KEY` for the GitHub App. (See https://release-plz.ieni.dev/docs/github/token#use-a-github-app for setup)
* `CARGO_REGISTRY_TOKEN` for publishing to crates.io
GitHub repo further needs to be configured to allow GitHub actions to create and approve pull requets. See
https://release-plz.ieni.dev/docs/github/quickstart#1-change-github-actions-permissions
---
@ethanpailes we also need you to change the above repo settings and setup the workflow since I don't have admin access to the repo.
I've tested the release-plz to make sure its changelog …
> ci: add automated release and publish workflow

- libshpool/src/config.rs
- libshpool/src/daemon/shell.rs
This patch tunes the default width for our in-memory terminal used for session restoration and adds a user controllable knob. This is a short term bandaid for #72, but doesn't really address the core issue.
> fix: tune vt100 memory usage

- .github/ISSUE_TEMPLATE/bug_report.md
Mostly, I want to instruct people on how to pull logs without the journalctl prefix since the logging framework already adds a log prefix. I took the opportunity to tweak some phrasing as well though.
> chore: tweak bug report template

- Cargo.lock
- libshpool/Cargo.toml
- libshpool/src/daemon/server.rs
- libshpool/src/protocol.rs
This patch switches us from using bincode, which has pretty terrible forwards compatibility properties
to using msgpack (I think I did a switch in the
previous direction in the past). bincode is faster, but we don't actually care about encoding speed
since we are just encoding some tiny baby little
headers at the start of a connection. This
change also adds a bunch of #[serde(default)]
annotations, which should take care of the second
half of forwards compatibilty.
This means one last protocol version break before
hopefully being able to evolve the protocol in a
much more civilized manner.
I realized I was going to have to add a protocol
field for #47, so this should be done first.
Fixes #85
> fix: protocol forward compat

- Cargo.lock
- Cargo.toml
- shpool-protocol/Cargo.toml
- shpool-protocol/src/lib.rs
This patch copies all the types from protocol.rs
(plus tty::Size) into a new shpool-protocol
crate. All the methods hanging off of them
are stripped out, since this crate is meant
to kept as purely a place for types to live.
Once this crate is published, the next step is
to move all the methods to Ext traits and
delete the old types, then we can implement
some logic to do version negotiation as
described by #88
> feat: move protocol types to their own crate

- HACKING.md
This patch adds a formalish version policy to
our dev docs. It can be a little murky about what
counts as a breaking change, and this should hopefully clarify things going forward and help keep us consistent.
> doc: document version policy

- Cargo.lock
- libshpool/Cargo.toml
- libshpool/src/attach.rs
- libshpool/src/daemon/pager.rs
- libshpool/src/daemon/server.rs
- libshpool/src/daemon/shell.rs
- libshpool/src/daemon/show_motd.rs
- libshpool/src/detach.rs
- libshpool/src/kill.rs
- libshpool/src/list.rs
- libshpool/src/protocol.rs
- libshpool/src/tty.rs
- shpool/tests/daemon.rs
- shpool/tests/support/daemon.rs
This patch migrates us from the old protocol
module to the new protocol crate. The logic
remains in the protocol module in the form
of the client struct and the new ChunkExt
extension trait since the methods don't
belong in the protocol description itself.
This does not yet add the version negotiation
logic that we will need before our next release,
but it does get us one step closer to resolving
issue #88.
> fix: migrate to new shpool-protocol crate

- Cargo.lock
- libshpool/Cargo.toml
- libshpool/src/attach.rs
- libshpool/src/daemon/server.rs
- libshpool/src/detach.rs
- libshpool/src/kill.rs
- libshpool/src/list.rs
- libshpool/src/protocol.rs
- shpool-protocol/Cargo.toml
- shpool-protocol/src/lib.rs
- shpool/tests/attach.rs
- shpool/tests/detach.rs
- shpool/tests/kill.rs
- shpool/tests/list.rs
This patch adds some version negotiation logic
and appropriate warnings to shpool. Shpool remains permissive about version mismatches, only issuing
warnings so that the user may continue to perform
any operations which still function correctly, but it now provides recommendations on how to
address the issue.
The protocol version is determined by the new
shpool-protocol crate.
Fixes #88
> fix: add version negotiation warnings

- release-plz.toml
* shpool will use vx.y.z tag same as before
+ libshpool won't get a separate tag since it's always the same version as shpool
+ other crates by default uses package-vx.y.z tag
* GitHub release is only created for shpool
* Enable change log generation for shpool-protocol
Unfortunately release-plz doesn't support different changelog formats, so shpool-protocol will use the same debian style we have for shpool and libshpool.
Fixes #100.
> ci: tweak release-plz for multiple crates

- libshpool/src/daemon/shell.rs
- shpool/tests/attach.rs
- shpool/tests/data/restore_screen.toml
- shpool/tests/support/attach.rs
- shpool/tests/support/line_matcher.rs
This patch starts correctly suppressing the prompt setup code during screen restore. Previously, we
were just suppressing it in terms of the data
we initially stream to the user, but if you create a new session, then disconnect, then reconnect, the setup code would be visible. The fix is to avoid pumping data into the in-memory term until after we've seen the prompt setup sentinel.
I tested that the tweaked test in this patch failes without the application change to ensure that it
is really testing what we want. I also observed this patch working with manual testing.
Fixes #120
> fix: suppress prompt setup in screen restore

- libshpool/src/daemon/pager.rs
- libshpool/src/daemon/server.rs
- libshpool/src/daemon/show_motd.rs
- shpool/tests/attach.rs
- shpool/tests/data/motd_env_test_script.sh
- shpool/tests/data/motd_pager_env_test.toml.tmpl
This patch fixes the motd.pager mode to start launching the pager with the same environment that we launch the shell with. The old way of just inheriting the same environment that the daemon has has the problem that it will not correctly match the user's TERM value, which can cause problems for programs like `less` that use the TERM value to determine the right control sequences to emit.
Fixes #129
> fix: forward shell env to pager

- libshpool/src/daemon/server.rs
- libshpool/src/daemon/shell.rs
- libshpool/src/daemon/ttl_reaper.rs
This patch adds some span traces at all the points we take locks on the global shells table, the pager_ctl handle and the shell_to_client_ctl handle. This should hopefully make it a bit easier to identify
deadlocks.
> feat: add span traces at lock() points

- libshpool/src/daemon/shell.rs
- libshpool/src/protocol.rs
- shpool/tests/attach.rs
- shpool/tests/detach.rs
This patch fixes the exit code for the attach
process so that it is 0 when shpool has been
told to gracefully detach, either via the
`shpool detach` subcommand or via the detach
keybinding. It is more semantically correct
to exit 0 in these cases.
Fixes #130
BREAKING CHANGE: technically could impact some scripts
> fix: exit success for graceful detaches

- README.md
This is a fairly common thing to want to do,
we should include it in our README. Currently,
you need to go digging in CONFIG.md.
> docs: document detach keybinding in README

- libshpool/src/daemon/prompt.rs
This prefixes the sentinel commands we use to
bracket the prompt setup code with a space in order to prevent them from cluttering up the history.
It might not work for all shells, but hopefully
it will improve things a little.
This was brought up in #120 (though it isn't the
main problem from that bug).
> fix: suppress prompt sentinels from history

- libshpool/src/daemon/server.rs
- libshpool/src/daemon/show_motd.rs
- shpool/tests/attach.rs
We were caching some config values, which is a no-no now that we support dynamic config reloading. The
fix is to just always store the manager and access config fields at the last minute as we are supposed to.
> fix: handle dyn config updates to motd settings

- libshpool/src/daemon/keybindings.rs
The documented grammar for keybindings was slightly wrong since it did not show that you need to seperate chords in a sequence with whitespace. This patch
fixes that.
> fix: add space to keybindings grammar

- libshpool/src/config_watcher.rs
- libshpool/src/daemon/server.rs
- libshpool/src/daemon/shell.rs
- libshpool/src/test_hooks.rs
- shpool/tests/attach.rs
- shpool/tests/detach.rs
- shpool/tests/kill.rs
This patch attempts to reduce the potential to deadlock in the shell->client thread by removing the mutex lock around the shell->client unix socket stream. While recent changes to reduce deadlocks have successfully prevented a single locked session from gumming up all the other sessions, the core issue seems to be persisting. I don't see a smoking gun in the logs that a reporter sent me, but reducing the number of locks in the shell->client thread, which seems to be the one that gets locked up, might help. This should also be slight better for performance (not that it really matters here).
In addition to that main change, this patch contains a few little bugfixes:
- Previously, every time the client probed for daemon presence, the daemon would put a distracting stack trace in its log. …
> fix: reduce deadlock potential in shell->client

- .cargo/config.toml
This configures cargo to use the MSRV aware resolver, which should hopefully prevent future release woes.
> fix: use MSRV aware resolver

- Cargo.lock
- libshpool/Cargo.toml
This upgrades the notify crate to 7.0.0. We can't go all the way to 8.0.0 the way dependabot wants to because it will break our MSRV.
> chore: upgrade notify crate

- libshpool/src/daemon/shell.rs
We have some duplicate error context strings.
This patch differentiates them.
> chore: differentiate error contexts

- libshpool/src/daemon/shell.rs
I thought we had already dealt with this bug, but apparently not. This patch fixes the shell->client thread to always use VTERM_WIDTH when resizing the in memory terminal.
> fix: vterm width

- Cargo.lock
- libshpool/Cargo.toml
- libshpool/src/lib.rs
These colors look nice when sent to a terminal, but are really annoying when in a log file. I mostly interact with logs when users post them due to bugs, so getting rid of the colors will make life easier.
> fix: remove ansi color codes from logs

- deny.toml
Cargo deny is complaining that instant is unmaintained. This suppresses the warning.
> chore: allow instant crate

- Cargo.lock
- libshpool/Cargo.toml
- shpool/Cargo.toml
- shpool/tests/daemon.rs
This patch updates our nix dependency to 0.29.
We didn't have to do anything for libshpool, but
I had to make some tweaks to the test code. I
was even able to delete an `unsafe` block, which
is always nice.
> chore: upgrade nix to 0.29

- Cargo.lock
- libshpool/Cargo.toml
- libshpool/src/daemon/server.rs
- shpool-protocol/Cargo.toml
- shpool-protocol/src/lib.rs
This patch adds a new dynamic log level adjustment message to the shpool-protocol crate. This is a
breaking change for the protocol, but won't result in a breaking change for libshpool.
This is progress on #117
> feat: add dynamic log level msg to shpool-protocol

- .github/workflows/publish.yml
The release pipeline is still broken even after my attempt to fix it with b99a1af6.
https://github.com/shell-pool/shpool/actions/runs/13316122235/job/37190478131#step:5:292 shows the problem.
> fix: release plz pipeline

- libshpool/src/daemon/mod.rs
- libshpool/src/daemon/server.rs
- libshpool/src/lib.rs
- libshpool/src/set_log_level.rs
- shpool/tests/daemon.rs
- shpool/tests/list.rs
- shpool/tests/support/daemon.rs
This patch adds a new subcommand to allow dynamically changing
the log level. This should hopefully make it easier to debug
some issues where we can't restart to crank up the verbosity.
Fixes #117
BREAKING CHANGE: the libshpool api has has a new enum variant
> feat: allow daemon log level to dynamically change

- libshpool/src/daemon/pager.rs
- libshpool/src/daemon/server.rs
- libshpool/src/daemon/show_motd.rs
- shpool/tests/attach.rs
This patch teaches shpool to dump the environment
forwarded from the attach shell in $SHPOOL_SESSION_DIR/forard.env on every reattach. Previously, these env var bindings would only impact the initial environment when the shell is first spawned. Dumping the vars to a file allows users to keep their environment up to date via scripts if they so desire.
This should help a little with #111, though it doesn't solve the issue perfectly.
I'll need to follow this up with documentation once it merges and gets released. We may also want to consider doing something like automatically touching a
$SHPOOL_SESSION_DIR/forward.env.needs_refresh
file on reattach and then sourcing forward.env and removing the marker file within our prompt hook.
> feat: dump forward_env in file

- libshpool/src/daemon/prompt.rs
👋 hey Ethan, awesome project! Excited to forget how to reconfigure tmux to have vim keybindings (that still don't really make sense to me 😅).
This PR attempts to fix #95
I was running into this same issue on some of my machines. Looks like some distros, when using bash, may set `$PROMPT_COMMAND` to something with whitespace. Though, I'm curious if there's a case where we wouldn't want to `eval ${PROMPT_COMMAND}`.
```shell
builder@android-builder:~$ shpool attach main
shpool:main builder@android-builder:~$
builder@android-builder:~$ echo $PROMPT_COMMAND
builder@android-builder:~$ echo $PS1
\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$
```
```shell
root@bunt:~# echo $PROMPT_COMMAND
root@bunt:~# echo $PS1
\[\e]0;\u@\h: …
```
> fix: eval SHPOOL__OLD_PROMPT_COMMAND rather than iterate sub-components
